version: "2"
services:
  nagvis:
   image: rahonabe/nagvis
   env_file: ./secrets.env
   hostname: nagvis
   build: 
    context: ./nagvis
   volumes:
     - ./nagvis-container/webroot_nagvis:/usr/local/nagvis
     - ./nagvis-container/lib/php5/sessions:/var/lib/php5/sessions
     - ./nagvis-container/log/apache2:/var/log/apache2
     - ./nagvis-container/certs:/etc/apache2/ssl:ro
   network_mode: "host"
