#!/bin/bash

#Set localtime
unlink /etc/localtime
ln -s /usr/share/zoneinfo/${LOCALTIME} /etc/localtime
echo "Time set to ${LOCALTIME}"

##Config: we separate db config from file config

#If we cannot find nagvis conf, run conf script
if [ ! -f "/usr/local/nagvis/etc/nagvis.ini.php" ]; then

/opt/setup/nagvis

fi

sed -i 's/:80/:8080/' /etc/apache2/sites-available/*
sed -i 's/Listen 80/Listen 8080/' /etc/apache2/ports.conf 
#Ensure that nagvis site is enabled
if [ ! -f "/etc/apache2/sites-enabled/nagvis.conf" ]; then
a2ensite nagvis
fi


#Check for an available internet connection
if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
ntpd -gq
service ntp start
fi


/usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n &
trap "supervisorctl shutdown && wait" SIGTERM
wait
